version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: service_analytics_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/V1__schema_init.sql:/docker-entrypoint-initdb.d/1_schema_init.sql
      - ./sql/V2__kpi_views.sql:/docker-entrypoint-initdb.d/2_kpi_views.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d analytics_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
